---
# This playbook deploys the whole application stack in this site.  

- name: apply common configuration to nodes group
  #hosts: nodes
  hosts: ts
  user: uraniumadm
  become_user: root
  roles:
    - ipmitool
