---
# This playbook deploys the whole application stack in this site.  

#- name: apply common configuration to nodes group
#  hosts: test
#  become: true
#  user: uraniumadm
#  become_user: root
#  vars:
#      ldap: "true"
#  roles:
#    - infiniband
#    - influxdb
#    - telegraf
#    - kapacitor
#    - chronograf


- name: Install Slurm Database
  hosts: nodedatabase
  become: true
  user: uraniumadm
  become_user: root
  roles:
    - munge
    - slurmPush
    - slurminstallrpms
    - slurmdbd


