---

# Variables for role keepalived

keepalived_auth_pass: "1111"
keepalived_role: "MASTER"
keepalived_router_id: "110"
keepalived_shared_iface: "enp0s3"
keepalived_shared_ip: "130.223.30.78"
keepalived_check_process: "keepalived"
keepalived_priority: "100"
keepalived_backup_priority: "50"
