
- include_vars: group_vars/slurm

# Add Slurm
- name: add slurm group
  group: name={{ slurmgroupname }} gid={{ slurmgid }} state=present
  tags: slurm

- name: add user slurm
  user: name={{ slurmname }} group={{ slurmgroupname }} comment="Slurm workload manager" home=/var/lib/{{ slurmname }} uid={{ slurmuid }} shell=/bin/bash state=present
  tags: slurm


- name: push slurm.conf
  template: src=slurm.conf.j2 dest=/etc/slurm/slurm.conf

- name: create /var/spool/slurmd
  file: path=/var/spool/slurmd state=directory owner={{ slurmname }} mode=0755

- name: create /var/spool/slurmd
  template: src=cgroup.conf dest=/etc/slurm/cgroup.conf

- name: ensure that slurmd is started
  systemd: name=slurmd state=started
  when: slurmd is defined

- name: ensure that slurmd is started
  systemd: name=slurmctld state=started
  when: slurmctld is defined