---
galaxy_info:
  author: Christophe Bovigny
  description: "Role for setting up keepalived"
  company: SIB
  license: license (Apache)
  min_ansible_version: 1.5
  platforms:
  - name: EL
    versions:
    - 5
    - 6
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  categories:
  - system
dependencies: []
