---
# This role installs and sets up memory limits to unlimited


- name: Push unlimited memory file (Centos)
  template: src=limits.conf dest=/etc/security/limits.conf owner=root group=root
  tags: rdma


- name: Install vim / net-tools / libselinux-python / libsemanage-python /bind-utils / wget / nano / bc
  yum: name={{ item }} state=present
  with_items:
   - vim
   - net-tools
   - libselinux-python
   - libsemanage-python
   - bind-utils
   - wget
   - nano
   - bc
  tags: util


- name: check if /opt/{{ jdkversion }}.tar.gz exist
  stat: path=/opt/{{ jdkversion }}.tar.gz
  register: javaexist
  tags: java

- name: Download Java
  get_url:
    url: "{{jdkdownloadurl}}"
    dest: "/opt"
    headers: 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie; --no-check-certificate'     
  when: not javaexist.stat.exists
  tags: java
  
- name: untar {{ jdkversion }}.tar.gz
  unarchive: src=/opt/{{ jdkversion }}.tar.gz dest=/opt remote_src=True
  when: not javaexist.stat.exists
  tags: java

- name: java | alternative
  template: src=alternatives2.sh.j2 dest=/opt/alternatives.sh mode=755
  tags: java

- name: Java | alternative script run
  command: /usr/bin/bash /opt/alternatives.sh
  tags: java

- name: push java.sh in /etc/profile.d/
  template: src=java.sh.j2 dest=/etc/profile.d/java.sh
  tags: java


