- include_vars: group_vars/telegraf

- name: Push repos files
  template: src=influxdata.repo.j2 dest=/etc/yum.repos.d/influxdata.repo owner=root group=root mode=0755
  tags:
    - influxdata

- name: install telegraf
  yum: name=telegraf state=present
  tags:
    - telegraf

- name: push telegraf.conf
   template: src=influxdata.repo.j2 dest=/etc/yum.repos.d/influxdata.repo owner=root group=root mode=0755